services:
  nr_ue19:
    image: docker_ueransim
    container_name: nr_ue19
    stdin_open: true
    tty: true
    volumes:
      - ../ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../.env
    environment:
      - COMPONENT_NAME=ueransim-ue19
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_UE19_IP}
networks:
  default:
      name: docker_open5gs_default
      external: true
