FROM python:3.11-slim

# Nainštalujeme potrebné knižnice
RUN pip install flask prometheus_client pygtail

# Nastavíme pracovný adresár
WORKDIR /app

# Skopírujeme Python súbor do obrazu
COPY log_watcher.py .

# Otvoríme port
EXPOSE 9000

# Spustíme skript
CMD ["python", "log_watcher.py"]
