FROM python:3.11-slim

# Nainštalujeme potrebné knižnice
RUN pip install \
    numpy==1.26.4 \
    tensorflow==2.19.0 \
    scikit-learn \
    flask \
    prometheus_client \
    pygtail \
    joblib \
    schedule \
    pandas

# Nastavíme pracovný adresár
WORKDIR /app

# Skopírujeme Python súbor do obrazu
COPY log_watcher.py .

# Otvoríme port
EXPOSE 9000

# Spustíme skript
CMD ["python", "log_watcher.py"]
