server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail-positions.yaml  # ✅ Safe temp path


clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: open5gs_amf
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          component: amf
          __path__: /Users/davidtruhlar/Documents/FIIT/BP/5GDigitalTwin/Implementation/log/amf.log

  - job_name: open5gs_ausf
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          component: ausf
          __path__: /Users/davidtruhlar/Documents/FIIT/BP/5GDigitalTwin/Implementation/log/ausf.log

  - job_name: open5gs_pcf
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          component: pcf
          __path__: /Users/davidtruhlar/Documents/FIIT/BP/5GDigitalTwin/Implementation/log/pcf.log

  - job_name: open5gs_smf
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          component: smf
          __path__: /Users/davidtruhlar/Documents/FIIT/BP/5GDigitalTwin/Implementation/log/smf.log

  - job_name: open5gs_upf
    static_configs:
      - targets: [localhost]
        labels:
          job: open5gs
          component: upf
          __path__: /Users/davidtruhlar/Documents/FIIT/BP/5GDigitalTwin/Implementation/log/upf.log