#version: '3'
services:
  srsue_5g_zmq3:
    image: docker_srslte
    container_name: srsue_5g_zmq3
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_5g_zmq3
      - MCC=001
      - MNC=01
      - SRS_UE3_IP=172.22.0.49
      - SRS_GNB_IP=172.22.0.37
      - UE3_KI=8baf473f2f8fd09487cccbd7097c6864
      - UE3_OP=33333333333333333333333333333333
      - UE3_IMSI=001011234567897
      - UE3_IMEI=356938035643803
    expose:
      - "2004/tcp"
      - "2005/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE3_IP}
networks:
  default:
    name: docker_open5gs_default
    external: true