#version: '3'
services:
  srsue_5g_zmq2:
    image: docker_srslte
    container_name: srsue_5g_zmq2
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=ue_5g_zmq2
      - SRS_UE1_IP=172.22.0.48
      - SRS_GNB_IP=172.22.0.37
      - UE1_KI=8baf473f2f8fd09487cccbd7097c6863
      - UE1_OP=22222222222222222222222222222222
      - UE1_IMSI=001011234567896
      - UE1_IMEI=356938035643803
    expose:
      - "2002/tcp"
      - "2003/tcp"
    networks:
      default:
        ipv4_address: ${SRS_UE2_IP}
networks:
  default:
    name: docker_open5gs_default
    external: true