{
 "title": "Current state Dash",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Networks current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered UEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ran_ue{job=\"amf\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "gNodeBs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnb{instance=\"172.22.0.10:9091\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 1 },
   "targets": [
    { "expr": "amf_session", "legendFormat": "{{job}}" },
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "fivegs_pcffunction_pa_sessionnbr",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "fivegs_smffunction_sm_sessionnbr",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Prediction (placeholder)", "type": "text", "gridPos": { "h": 5, "w": 6, "x": 15, "y": 1 }, "options": { "content": "Placeholder for prediction" } },
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job!=\"mme\", job!=\"netdata\", job!=\"logwatcher\", instance!=\"host.docker.internal:9000\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time of UE registration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 1, "y": 6 },
   "targets": [
    {
     "expr": "ue_registration_duration_seconds_avg",
     "legendFormat": "Avg"
    },
    {
     "expr": "ue_registration_duration_seconds_min",
     "legendFormat": "Min"
    },
    {
     "expr": "ue_registration_duration_seconds_max",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Time of UE session",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "ue_session_duration_seconds_avg",
     "legendFormat": "Avg"
    },
    {
     "expr": "ue_session_duration_seconds_min",
     "legendFormat": "Min"
    },
    {
     "expr": "ue_session_duration_seconds_max",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "AMF Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 11, "x": 1, "y": 11 },
   "targets": [
    {
     "expr": "{filename=\"/mnt/logs/amf.log\"} != `[metrics]` != `LOCAL` != `UTC` != `daemon`"
    }
   ]
  },
  {
   "title": "AMF Warnings",
   "type": "logs",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{filename=\"/mnt/logs/amf.log\"} |= `WARNING`"
    }
   ]
  }
 ]
}