{
 "title": "Open5Gs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "UPF - GTP Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_ep_n3_gtp_indatapktn3upf",
     "legendFormat": "__auto"
    },
    {
     "expr": "fivegs_ep_n3_gtp_outdatapktn3upf",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPF - Active Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active UEs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "ues_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MME - Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "enb_ue", "legendFormat": "__auto" }
   ]
  }
 ]
}