{
 "title": "Current state Dash",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Networks current state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Registered UEs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ran_ue", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "gNodeBs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gnb", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "targets": [
    { "expr": "amf_session", "legendFormat": "{{job}}" },
    {
     "expr": "fivegs_upffunction_upf_sessionnbr",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "fivegs_pcffunction_pa_sessionnbr",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "fivegs_smffunction_sm_sessionnbr",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Current State (classification)",
   "type": "stat",
   "description": "Model with BatchNormalization",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "classified_uc_class", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "up{job!=\"mme\", job!=\"logwatcher\", instance!=\"host.docker.internal:9000\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Classified UCs over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 6 },
   "targets": [
    { "expr": "classified_uc_class", "legendFormat": "Classified UC" },
    { "expr": "true_uc_class", "legendFormat": "Real UC" }
   ]
  },
  {
   "title": "Confidence",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "classified_uc_confidence * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 6 },
   "targets": [
    { "expr": "model_loss", "legendFormat": "Max" }
   ]
  },
  {
   "title": "Selected features",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "fivegs_smffunction_sm_n4sessionreportsucc_value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_n4sessionreportsucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fivegs_pcffunction_pa_sessionnbr_value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_sessionnbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fivegs_pcffunction_pa_policysmassosucc_value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "fivegs_pcffunction_pa_policysmassosucc",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fivegs_smffunction_sm_pdusessioncreationreq_value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_pdusessioncreationreq",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fivegs_smffunction_sm_qos_flow_nbr_value",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "fivegs_smffunction_sm_qos_flow_nbr",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "{job=\"open5gs\"}"
    }
   ]
  }
 ]
}