version: '3'
services:
  nr_ue2:
    image: docker_ueransim
    container_name: nr_ue2
    stdin_open: true
    tty: true
    volumes:
      - ./ueransim:/mnt/ueransim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .custom_env
    environment:
      - COMPONENT_NAME=ueransim-ue2
    expose:
      - "4997/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      default:
        ipv4_address: ${NR_UE2_IP}
networks:
  default:
    external:
      name: docker_open5gs_default
